### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by agalliazzo** [openthread/ot-br-posix#2290]
Hi Guys,
I just updated my local sources with the latest commit but otbr now is unable to compile... 
The error here:

```
[9/77] Building CXX object src/border_agent/CMakeFiles/otbr-border-agent.dir/border_agent.cpp.o
FAILED: src/border_agent/CMakeFiles/otbr-border-agent.dir/border_agent.cpp.o
/usr/bin/c++ -DOTBR_ENABLE_BACKBONE_ROUTER=1 -DOTBR_ENABLE_BORDER_AGENT=1 -DOTBR_ENABLE_BORDER_ROUTING=1 -DOTBR_ENABLE_BORDER_ROUTING_COUNTERS=1 -DOTBR_ENABLE_DBUS_SERVER=1 -DOTBR_ENABLE_DHCP6_PD=0 -DOTBR_ENABLE_DNSSD_DISCOVERY_PROXY=1 -DOTBR_ENABLE_EPSKC=1 -DOTBR_ENABLE_LINK_METRICS_TELEMETRY=0 -DOTBR_ENABLE_MDNS_MDNSSD=1 -DOTBR_ENABLE_NAT64=0 -DOTBR_ENABLE_NOTIFY_UPSTART=1 -DOTBR_ENABLE_PUBLISH_MESHCOP_BA_ID=1 -DOTBR_ENABLE_REST_SERVER=1 -DOTBR_ENABLE_SRP_ADVERTISING_PROXY=1 -DOTBR_ENABLE_SRP_SERVER_AUTO_ENABLE_MODE=1 -DOTBR_ENABLE_TREL=1 -DOTBR_ENABLE_VENDOR_INFRA_LINK_SELECT=0 -DOTBR_MESHCOP_SERVICE_INSTANCE_NAME="\"OpenThread BorderRouter\"" -DOTBR_PACKAGE_NAME=\"OpenThread_BorderRouter\" -DOTBR_PACKAGE_VERSION=\"0.3.0-a2cfdd3-dirty\" -DOTBR_PRODUCT_NAME=\"BorderRouter\" -DOTBR_SYSLOG_FACILITY_ID=LOG_USER -DOTBR_VENDOR_NAME=\"OpenThread\" -I/home/pi/ot-br-posix/include -I/home/pi/ot-br-posix/src -I/home/pi/ot-br-posix/build/otbr/third_party/openthread/repo/etc/cmake -I/home/pi/ot-br-posix/third_party/openthread/repo/etc/cmake -I/home/pi/ot-br-posix/third_party/openthread/repo/include -I/home/pi/ot-br-posix/third_party/openthread/repo/src/posix/platform/include -I/home/pi/ot-br-posix/third_party/openthread/repo/src -Wall -Wextra -Werror -Wfatal-errors -Wuninitialized -Wno-missing-braces -std=c++11 -MD -MT src/border_agent/CMakeFiles/otbr-border-agent.dir/border_agent.cpp.o -MF src/border_agent/CMakeFiles/otbr-border-agent.dir/border_agent.cpp.o.d -o src/border_agent/CMakeFiles/otbr-border-agent.dir/border_agent.cpp.o -c /home/pi/ot-br-posix/src/border_agent/border_agent.cpp
/home/pi/ot-br-posix/src/border_agent/border_agent.cpp: In member function ‘void otbr::BorderAgent::Start()’:
/home/pi/ot-br-posix/src/border_agent/border_agent.cpp:207:5: error: ‘otBorderAgentSetEphemeralKeyCallback’ was not declared in this scope
  207 |     otBorderAgentSetEphemeralKeyCallback(mNcp.GetInstance(), BorderAgent::HandleEpskcStateChanged, this);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It seems introduced with commit https://github.com/openthread/ot-br-posix/commit/4b545bc9df73c00b3a6539d58d0824cddb1a9eb3, maybe a file not pushed on the commit?

Best

**Comment by jwhui** [comment]
Did you update your submodules?
```
 git submodule update --recursive
```

**Comment by agalliazzo** [comment]
No... and of course, your suggestion worked... 
as far as it seem my focus is start to fade out... sorry for bothered you...

When I miss these basic stuff I feel so dumb :)
